import { StyleSheet } from 'react-native';

/** Thème POS terrain — lisible, contrasté, sans décor superflu. */
export const colors = {
  bg: '#F3F5F4',
  surface: '#FFFFFF',
  surfaceMuted: '#E8EEEC',
  text: '#0F172A',
  muted: '#64748B',
  border: '#D5DDD9',
  hair: '#E5EBE8',
  accent: '#0F766E',
  accentSoft: '#CCFBF1',
  accentText: '#134E4A',
  danger: '#B91C1C',
  dangerSoft: '#FEE2E2',
  warning: '#B45309',
  warningSoft: '#FEF3C7',
  link: '#0F766E',
  btn: '#0F766E',
  btnText: '#FFFFFF',
  chipOn: '#CCFBF1',
  tabInactive: '#94A3B8',
  ok: '#047857',
};

export const ui = StyleSheet.create({
  wrap: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 52,
    paddingBottom: 96,
    gap: 12,
    backgroundColor: colors.bg,
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    padding: 24,
    backgroundColor: colors.bg,
  },
  brand: {
    fontSize: 13,
    letterSpacing: 2.4,
    fontWeight: '800',
    color: colors.accent,
    textTransform: 'uppercase',
  },
  title: {
    fontSize: 26,
    fontWeight: '800',
    color: colors.text,
    letterSpacing: -0.4,
  },
  subtitle: { fontSize: 15, color: colors.muted, lineHeight: 21 },
  body: { fontSize: 16, color: colors.text },
  muted: { color: colors.muted, fontSize: 13, lineHeight: 18 },
  error: {
    color: colors.danger,
    backgroundColor: colors.dangerSoft,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    overflow: 'hidden',
    fontSize: 13,
    fontWeight: '600',
  },
  success: {
    color: colors.ok,
    backgroundColor: colors.chipOn,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    overflow: 'hidden',
    fontSize: 13,
    fontWeight: '600',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: colors.surface,
    color: colors.text,
  },
  btn: {
    backgroundColor: colors.btn,
    paddingVertical: 15,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  btnOff: { opacity: 0.38 },
  btnGhost: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    backgroundColor: colors.surface,
  },
  btnText: { color: colors.btnText, fontWeight: '700', fontSize: 16 },
  btnGhostText: { color: colors.text, fontWeight: '600' },
  link: { color: colors.link, fontWeight: '700', fontSize: 13 },
  chip: {
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    backgroundColor: colors.surface,
  },
  chipOn: {
    backgroundColor: colors.chipOn,
    borderColor: colors.accent,
  },
  chipText: { color: colors.text, fontWeight: '600', fontSize: 13 },
  chipTextOn: { color: colors.accentText, fontWeight: '700', fontSize: 13 },
  card: {
    borderWidth: 1,
    borderColor: colors.hair,
    borderRadius: 14,
    padding: 14,
    gap: 6,
    backgroundColor: colors.surface,
  },
  kpi: { fontSize: 22, fontWeight: '800', color: colors.text },
  headerActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
  },
  iconBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
});
