ALTER TYPE "TypeSourceComptable" ADD VALUE IF NOT EXISTS 'OD_MANUELLE';
ALTER TYPE "TypeSourceComptable" ADD VALUE IF NOT EXISTS 'CLOTURE_EXERCICE';
ALTER TYPE "TypeSourceComptable" ADD VALUE IF NOT EXISTS 'A_NOUVEAUX';
